import type { LayoutId, LayoutSystem } from "@/types";

export const LAYOUT_SYSTEMS: LayoutSystem[] = [
  {
    id: "single-hero",
    name: "Single Hero",
    description: "One dominant focal object with cinematic lighting and minimal background.",
    bestUse: "Product launches, luxury branding, hero ads",
    principles: ["Focal hierarchy", "Cinematic lighting", "Negative space"],
    gradient: "from-zinc-900 via-zinc-800 to-amber-950/40",
  },
  {
    id: "split-screen",
    name: "Split Screen",
    description: "Vertical or horizontal split for comparison and transformation narratives.",
    bestUse: "SaaS, fitness, AI transformation",
    principles: ["Dual narrative", "Contrast pairing", "Clear division"],
    gradient: "from-slate-900 via-indigo-950 to-slate-800",
  },
  {
    id: "z-pattern",
    name: "Z Pattern",
    description: "Eye flow moves in Z shape — headline top-left, CTA bottom-right.",
    bestUse: "Conversion ads, landing visuals",
    principles: ["Scan path", "CTA placement", "Visual momentum"],
    gradient: "from-neutral-900 via-blue-950 to-cyan-950/30",
  },
  {
    id: "f-pattern",
    name: "F Pattern",
    description: "Copy-heavy composition optimized for left-aligned scanning flow.",
    bestUse: "Informational ads, B2B campaigns",
    principles: ["Text hierarchy", "Left alignment", "Information density"],
    gradient: "from-stone-900 via-stone-800 to-emerald-950/20",
  },
  {
    id: "central-focus",
    name: "Central Focus",
    description: "Everything supports a centered object with radial attention and symmetry.",
    bestUse: "Fashion, watches, cosmetics",
    principles: ["Radial balance", "Symmetry", "Object prominence"],
    gradient: "from-rose-950 via-zinc-900 to-rose-900/30",
  },
  {
    id: "grid-modular",
    name: "Grid Modular",
    description: "Structured blocks and repeating geometry with UI-driven composition.",
    bestUse: "SaaS, ecommerce, dashboards",
    principles: ["Modular grid", "Card systems", "Repeatable units"],
    gradient: "from-zinc-950 via-violet-950 to-zinc-800",
  },
  {
    id: "diagonal-dynamic",
    name: "Diagonal Dynamic",
    description: "Angled composition with strong motion direction and high energy.",
    bestUse: "Sports, automotive, gaming",
    principles: ["Diagonal tension", "Motion vectors", "Energy placement"],
    gradient: "from-orange-950 via-zinc-900 to-red-950/40",
  },
  {
    id: "editorial-magazine",
    name: "Editorial Magazine",
    description: "Large whitespace, elegant typography, and premium editorial photography.",
    bestUse: "Fashion, luxury, high-end campaigns",
    principles: ["Editorial rhythm", "Whitespace", "Premium type"],
    gradient: "from-neutral-950 via-stone-900 to-amber-900/20",
  },
  {
    id: "typography-dominant",
    name: "Typography Dominant",
    description: "Massive typography with minimal imagery — type becomes the hero.",
    bestUse: "Streetwear, events, branding campaigns",
    principles: ["Type scale", "Minimal imagery", "Bold statements"],
    gradient: "from-black via-zinc-900 to-purple-950/50",
  },
  {
    id: "floating-elements",
    name: "Floating Elements",
    description: "Layered floating objects with suspended UI and atmospheric depth.",
    bestUse: "Tech, AI products, futuristic ads",
    principles: ["Layered depth", "Suspension", "Atmosphere"],
    gradient: "from-slate-950 via-cyan-950 to-blue-950/40",
  },
  {
    id: "framed-content",
    name: "Framed Content",
    description: "Structured frame containers with windowed compositions and card systems.",
    bestUse: "Portfolio, product galleries, UI showcases",
    principles: ["Frame hierarchy", "Windowed views", "Contained focus"],
    gradient: "from-zinc-900 via-amber-950/20 to-zinc-800",
  },
  {
    id: "full-bleed",
    name: "Full Bleed",
    description: "Edge-to-edge imagery with cinematic immersion and large visuals.",
    bestUse: "Travel, automotive, lifestyle campaigns",
    principles: ["Edge-to-edge", "Immersion", "Scale impact"],
    gradient: "from-teal-950 via-zinc-900 to-emerald-950/30",
  },
  {
    id: "layered-depth",
    name: "Layered Depth",
    description: "Foreground, midground, and background with atmospheric blur.",
    bestUse: "Gaming, cinematic posters, product ads",
    principles: ["Depth planes", "Atmospheric blur", "Parallax feel"],
    gradient: "from-indigo-950 via-zinc-900 to-fuchsia-950/30",
  },
  {
    id: "mobile-native",
    name: "Mobile Native",
    description: "Platform-native social UI with organic content aesthetic.",
    bestUse: "TikTok, Instagram ads, UGC campaigns",
    principles: ["Native UI", "Social framing", "Organic feel"],
    gradient: "from-pink-950 via-zinc-900 to-purple-950/40",
  },
  {
    id: "carousel-sequential",
    name: "Carousel Sequential",
    description: "Story progression with multi-slide continuity and sequential narrative.",
    bestUse: "Storytelling ads, tutorials, product reveals",
    principles: ["Sequential flow", "Slide continuity", "Narrative arc"],
    gradient: "from-blue-950 via-zinc-900 to-violet-950/30",
  },
  {
    id: "asymmetrical",
    name: "Asymmetrical",
    description: "Uneven balance with creative tension and experimental composition.",
    bestUse: "Creative brands, modern campaigns",
    principles: ["Asymmetric tension", "Visual weight", "Experimentation"],
    gradient: "from-lime-950/30 via-zinc-900 to-orange-950/30",
  },
  {
    id: "radial",
    name: "Radial",
    description: "Orbiting composition with circular arrangement around a center.",
    bestUse: "Tech, wearables, futuristic visuals",
    principles: ["Radial orbit", "Circular energy", "Center gravity"],
    gradient: "from-violet-950 via-zinc-900 to-cyan-950/40",
  },
  {
    id: "timeline",
    name: "Timeline",
    description: "Progressive storytelling with step-by-step linear narrative.",
    bestUse: "Product journey, educational content",
    principles: ["Linear progression", "Step markers", "Journey flow"],
    gradient: "from-sky-950 via-zinc-900 to-indigo-950/30",
  },
  {
    id: "ui-showcase",
    name: "UI Showcase",
    description: "Interface as hero with glassmorphism, device framing, and product-first UI.",
    bestUse: "SaaS, apps, AI tools",
    principles: ["UI prominence", "Glass effects", "Device framing"],
    gradient: "from-slate-950 via-blue-950/50 to-indigo-950",
  },
  {
    id: "collage-scrapbook",
    name: "Collage Scrapbook",
    description: "Mixed media with layered textures, tape, paper, and photo composition.",
    bestUse: "Youth brands, music, fashion campaigns",
    principles: ["Mixed media", "Texture layers", "Organic collage"],
    gradient: "from-amber-950/40 via-zinc-900 to-rose-950/30",
  },
];

export const LAYOUT_MAP = Object.fromEntries(
  LAYOUT_SYSTEMS.map((l) => [l.id, l])
) as Record<string, LayoutSystem>;

/** Default image generation: first layout only (Single Hero) */
export const DEFAULT_SELECTED_LAYOUTS: LayoutId[] = [
  LAYOUT_SYSTEMS[0].id as LayoutId,
];
